# from base_prometheus.yml
global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: exporter
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['nginx-exporter:9113'] 

rule_files:
  - "/etc/prometheus/*.rules"

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alert-manager:9093
